# Generated by Django 3.1.7 on 2021-03-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="station",
            old_name="location",
            new_name="name",
        ),
    ]
