# Generated by Django 3.1.7 on 2021-04-06 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0002_auto_20210330_1919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
