# Generated by Django 3.2 on 2021-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0003_auto_20210406_1319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="state",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Working"), (1, "Blocked")], default=0
            ),
        ),
    ]
