# Generated by Django 3.2 on 2021-04-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0004_alter_station_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="state",
            field=models.CharField(
                choices=[("working", "Working"), ("blocked", "Blocked")],
                default="working",
                max_length=7,
            ),
        ),
    ]
