# Generated by Django 3.2 on 2021-04-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0005_alter_station_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="capacity",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
