# Generated by Django 3.2 on 2021-05-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0006_station_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="state",
            field=models.CharField(
                choices=[("working", "Working"), ("blocked", "Blocked")],
                default="working",
                editable=False,
                max_length=7,
            ),
        ),
    ]
