# Generated by Django 3.2.3 on 2021-06-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0007_alter_station_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="station",
            old_name="capacity",
            new_name="bikesLimit",
        ),
    ]
