# Generated by Django 3.2.3 on 2021-06-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0008_rename_capacity_station_bikeslimit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="state",
            field=models.CharField(
                choices=[("active", "Working"), ("blocked", "Blocked")],
                default="active",
                editable=False,
                max_length=7,
            ),
        ),
    ]
