# Generated by Django 3.2.3 on 2021-06-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0009_alter_station_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="station",
            old_name="state",
            new_name="status",
        ),
    ]
