# Generated by Django 3.1.7 on 2021-03-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0002_bike_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bike",
            old_name="state",
            new_name="status",
        ),
    ]
