# Generated by Django 3.2 on 2021-04-15 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0003_auto_20210406_1319"),
        ("bikes", "0004_auto_20210406_1319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stations.station",
            ),
        ),
        migrations.AlterField(
            model_name="bike",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Available"),
                    (1, "Rented"),
                    (2, "Reserved"),
                    (3, "Blocked"),
                ],
                default=0,
            ),
        ),
    ]
