# Generated by Django 3.2 on 2021-04-18 10:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0006_auto_20210415_1943"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reserved_at", models.DateTimeField()),
                ("reserved_till", models.DateTimeField()),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation",
                        to="bikes.bike",
                    ),
                ),
            ],
        ),
    ]
