# Generated by Django 3.2 on 2021-04-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0007_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("rented", "Rented"),
                    ("reserved", "Reserved"),
                    ("blocked", "Blocked"),
                ],
                default="available",
                max_length=9,
            ),
        ),
    ]
