# Generated by Django 3.2 on 2021-05-21 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bikes", "0009_reservation_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Malfunction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=1000)),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="malfunction",
                        to="bikes.bike",
                    ),
                ),
                (
                    "reporting_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="malfunctions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
