name: Lint

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@20.8b1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flakehell
      - name: Run flakehell
        run: |
          flakehell lint .
